# LiveKitC2CCall iOS Plugin - CocoaPods 配置
platform :ios, '14.0'
use_frameworks!

target 'LiveKitC2CCall' do
  # LiveKit Swift Client SDK（核心依赖）
  pod 'LiveKitClient', '~> 1.8.0'

  target 'LiveKitC2CCallTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'COCOAPODS=1']
        
        # 排除 arm64e 以兼容更多设备
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
